source 'https://gitlab.com/mediquo/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

def shared_pods
    pod 'MediQuo', '0.35.45'
end

target 'Mediquo Swift Example App' do
  shared_pods

  target 'Mediquo Swift Example AppTests' do
    inherit! :search_paths
  end

  target 'Mediquo Swift Example AppUITests' do
    inherit! :search_paths
  end
end
