source 'https://gitlab.com/mediquo/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

def shared_pods
    pod 'MediQuo', '~> 0.9'
    pod 'R.swift'
end

target 'Mediquo Swift Example App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
  # Pods for Mediquo Swift Example App

  target 'Mediquo Swift Example AppTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

  target 'Mediquo Swift Example AppUITests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

end
